name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!
    - type: input
      id: metabase_version
      attributes:
          label: Metabase version
          placeholder: v0.48.8
      validations:
          required: true
    - type: input
      id: bundle_version
      attributes:
          label: Bundle version
          placeholder: v0.48.8
      validations:
          required: true
    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: Also tell us, what did you expect to happen?
      validations:
          required: true
