services:

    metabase.token_generator:
        class: Malefici\Symfony\MetabaseBundle\Embedding\TokenGenerator
        arguments:
            - "%metabase.parameter.secret_key%"
            - "%metabase.parameter.token_expiration%"

    Malefici\Symfony\MetabaseBundle\Embedding\TokenGenerator:
        alias: 'metabase.token_generator'
        public: true

    metabase.url_generator:
        class: Malefici\Symfony\MetabaseBundle\Embedding\UrlGenerator
        arguments:
            - "@metabase.token_generator"
            - "%metabase.parameter.site_url%"
            - "%metabase.parameter.appearance%"

    Malefici\Symfony\MetabaseBundle\Embedding\UrlGenerator:
        alias: 'metabase.url_generator'
        public: true

    metabase.twig.extension:
        class: Malefici\Symfony\MetabaseBundle\Twig\MetabaseExtension
        arguments:
            - "@metabase.url_generator"
        tags: ['twig.extension']

    metabase.command.generate_token:
        class: Malefici\Symfony\MetabaseBundle\Command\EmbeddingGenerateTokenCommand
        arguments:
            - "@metabase.token_generator"
        tags: ['console.command']

    metabase.command.generate_url:
        class: Malefici\Symfony\MetabaseBundle\Command\EmbeddingGenerateUrlCommand
        arguments:
            - "@metabase.url_generator"
        tags: ['console.command']